server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: DateHikariCP #连接池名
      minimum-idle: 5 #最小空闲连接数
      idle-timeout: 180000 #空闲连接存活最大时间
      maximum-pool-size: 10 #最大连接数，默认为10
      auto-commit: true #从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间
      connection-timeout: 30000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #测试连接是否可用的查询语句

#mybatis-plus配置
mybatis-plus:
  type-aliases-package: com.example.server.pojo #配置mybatis数据返回类型的别名
  configuration:
    map-underscore-to-camel-case: false  #自动驼峰命名
  mapper-locations: classpath:*/mapper/*Mapper.xml

logging:
  level:
    com.example.server.mapper: debug


