server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    hikari:
      pool-name: DateHikariCP #连接池名
      minimum-idle: 5 #最小空闲连接数
      idle-timeout: 180000 #空闲连接存活最大时间
      maximum-pool-size: 10 #最大连接数，默认为10
      auto-commit: true #从连接池返回的连接自动提交
      max-lifetime: 1800000 #连接最大存活时间
      connection-timeout: 30000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #测试连接是否可用的查询语句
  redis:
    # Redis配置redis:
    timeout: 10000ms    # 连接超时时间
    host: 127.0.0.1   # Redis服务器地址
    port: 6379    # Redis服务器端口
    database: 0    # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024
        # 最大连接数，默认 8
        max-wait: 10000ms    # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200    # 最大空闲连接，默认 8
        min-idle: 5    # 最小空闲连接，默认 0


#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.server.pojo #配置mybatis数据返回类型的别名
  configuration:
    map-underscore-to-camel-case: false  #自动驼峰命名


logging:
  level:
    com.example.server.mapper: debug

jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yeb-secret
  # JWT的超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer




